services:
  frontend:
    build:
      context: ./weather-app   # replace with actual folder name
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./weather-api    # replace with actual folder name
    container_name: weather-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
