version: "3.9"

services:
  frontend:
    image: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: weather-backend
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
