version: "3.9"

services:
  frontend:
    build:
      context: https://github.com/SHAIKANASBASHA-55/weather-application.git#main:weather-app
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: https://github.com/SHAIKANASBASHA-55/weather-application.git#main:weather-api
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
