services:
  frontend:
    build:
      context: ./weather-app
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./weather-api
    container_name: weather-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - WEATHER_APP_ID=${WEATHER_APP_ID}
