version: "3.8"

services:
  frontend:
    build:
      context: ./weather-ui   # 👈 your actual frontend folder name
    container_name: weather-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./weather-api   # 👈 your actual backend folder name
    container_name: weather-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - WEATHER_APP_ID=${WEATHER_APP_ID}
